In [1]:
import numpy as np

Способы индексации в массивах

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [12]:
print a[0]
print a[0][0]
print a[0, 1]

[1 2 3 4]
1
2


 Указывая полуинтервал, можно вырезать куски массива, только необходимо помнить, что дочерний массив указывает на те же данные, что и массив-родитель.

In [13]:
print a
b = a[:2, 1:3]
print b

print a[0, 1]
b[0, 0] = 77
print a[0, 1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


Можно смешивать индексирование числами и вырезание полуинтервалами.

In [14]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print row_r1, row_r1.shape
print row_r2, row_r2.shape

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


Аналогично для столбцов

In [15]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print col_r1, col_r1.shape
print col_r2, col_r2.shape

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [17]:
a.dtype

dtype('int64')